---
- name: creates file in jail
  register: jail_test0
  sysrc:
    name: test_jail
    value: test
    jail: testjail

- name: jail file exists
  register: jail_file0
  stat:
    path: /usr/jails/testjail/etc/rc.conf

- name: validate jail works
  assert:
    that:
      - jail_test0 is changed
      - jail_file0.stat.exists