---
# tasks file for ansible-role-freebsd_kld

- name: Include {{ ansible_os_family }}.yml
  include_vars: "{{ ansible_os_family }}.yml"

- name: Assert that freebsd_kld has valid elements
  assert:
    that:
      - "'name' in item"
  with_items: "{{ freebsd_kld }}"

- name: Do load/unload freebsd_kld
  kld:
    name: "{{ item.name }}"
    load: "{{ item.load | default('yes') }}"
    boot: "{{ item.boot | default('yes') }}"
  with_items: "{{ freebsd_kld }}"
