---
# tasks file for ansible-role-freebsd_kld

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create log directory
  file:
    path: "{{ freebsd_kld_log_dir }}"
    mode: 0755
    owner: "{{ freebsd_kld_user }}"
    group: "{{ freebsd_kld_group }}"
    state: directory
  notify: Restart freebsd_kld

- name: Create db directory
  file:
    path: "{{ freebsd_kld_db_dir }}"
    mode: 0755
    owner: "{{ freebsd_kld_user }}"
    group: "{{ freebsd_kld_group }}"
    state: directory
  notify: Restart freebsd_kld

- name: Create freebsd_kld.conf
  template:
    src: freebsd_kld.conf.j2
    dest: "{{ freebsd_kld_conf_file }}"
    validate: echo %s
  notify: Restart freebsd_kld

- name: Start freebsd_kld
  service:
    name: "{{ freebsd_kld_service }}"
    enabled: true
    state: started
